image: ymc-docker-stages.artifactory-zci.enedis.fr/public/node:20

cache:
  key: npm
  policy: pull-push
  paths:
    - .npm/

before_script:
  - npm config set strict-ssl false
  - npm config set registry https://artifactory-zci.enedis.fr/artifactory/api/npm/proxy-npm-npmjs/
  - npm ci --cache .npm --prefer-offline

stages:
  - test
  - build
  - publish

variables:
  GOFAST:
    description: "Build & publish without testing jobs. Set input variable GOFAST manually to true on WEB UI"
    value: "false"
    options:
      - "true"
      - "false"
  TO_SNAPSHOTS:
    description: "Build & publish artifact to stages repository. Set input variable TO_SNAPSHOTS manually to true on WEB UI"
    value: "false"
    options:
      - "true"
      - "false"

# test-job:
#   stage: test
#   script:
#     - npm i
#     - npm run sonar
include:
  - local: ci/pipeline/mergeRequest.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  - local: ci/pipeline/main.yml
    rules:
      - if: $CI_PIPELINE_SOURCE == 'web' || $CI_PIPELINE_SOURCE == 'push'
